# TF-idf

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = ["This is the first document.", "This document is the second document.", "And this is the third one."]
vectorizer = TfidfVectorizer()
# Learn the vocabulary and IDF values
tfidf = vectorizer.fit(corpus)
# Transform the data into a TF-IDF representation
tfidf_matrix = vectorizer.fit_transform(corpus)

In [4]:
print(tfidf_matrix)

  (0, 1)	0.4694172843223779
  (0, 2)	0.6172273175654565
  (0, 6)	0.3645443967613799
  (0, 3)	0.3645443967613799
  (0, 8)	0.3645443967613799
  (1, 5)	0.47890874975914965
  (1, 1)	0.7284448965638161
  (1, 6)	0.2828512224204681
  (1, 3)	0.2828512224204681
  (1, 8)	0.2828512224204681
  (2, 4)	0.49711994139048143
  (2, 7)	0.49711994139048143
  (2, 0)	0.49711994139048143
  (2, 6)	0.2936070455647438
  (2, 3)	0.2936070455647438
  (2, 8)	0.2936070455647438


In [5]:
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer

# example input data
text = ["This is the first document.", "This is the second document.", "And this is the third one."]

# fit TfidfVectorizer on the input data
vectorizer = TfidfVectorizer()
vectorizer.fit(text)

# get the idf values as a dictionary
idf_dict = dict(zip(vectorizer.get_feature_names(), vectorizer.idf_))

print(idf_dict)

AttributeError: 'TfidfVectorizer' object has no attribute 'get_feature_names'

# MinMaxScaler

In [10]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

# Create a sample dataset
X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
             [10, 20, 30]])

# Create a scaler object
scaler = MinMaxScaler()

# Fit the scaler to the dataset and transform the data
X_scaled = scaler.fit_transform(X)

# Print the original and scaled data
print("Original data:\n", X)
print("Scaled data:\n", X_scaled)

Original data:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
Scaled data:
 [[0.         0.         0.        ]
 [0.33333333 0.16666667 0.11111111]
 [0.66666667 0.33333333 0.22222222]
 [1.         1.         1.        ]]


In [12]:
arr = np.array([ 1.08933069e-01 -2.84139284e-03 -5.27260316e-02  4.13724785e-01
   1.44465396e-01  1.38774996e-01  3.51667295e-01  6.54273964e-02
  -5.52708724e-02 -1.81993941e-01  4.22297880e-01  5.15880563e-02
  -3.05113273e-01  1.43349794e-01 -1.21152228e-01 -2.31597222e-01
  -3.07357543e-01  8.86052096e-02  4.03190722e-01 -7.37392502e-02
   2.07202403e-02 -1.12386612e-01 -2.57839782e-01 -6.27773106e-02
  -8.19788826e-02  1.22168045e-02  6.84443290e-02  1.46764473e-02
  -9.20043780e-02 -2.78895573e-01  4.08588581e-01  2.02044258e-01
   3.60652947e-01  4.43511064e-01 -1.89840198e-01 -1.09522139e-01
   3.20724274e-02 -4.31187695e-01  1.53092130e-01 -2.55831789e-01
  -3.26892584e-01  8.71650477e-02  2.41542970e-01  7.74605324e-03
  -5.07378702e-02 -2.35535227e-01 -2.07130574e-01  4.07378707e-01
   6.13721137e-02  1.40562137e-01 -9.87373653e-02 -5.71632981e-02
  -3.67666805e-01 -1.20163512e-01 -2.53284062e-01 -7.71040606e-02
  -9.01437296e-02 -1.33207548e-01  2.46512294e-02  8.34610891e-02
   2.43734613e-01 -1.96953384e-01  1.22644007e-04 -1.06559116e-01
   2.41587202e-01  1.02710898e-01 -9.92247527e-02  4.84431808e-02
   1.08371076e-01  3.72994889e-01 -3.56305325e-01 -9.28994560e-02
  -1.97235460e-01  2.24776106e-01 -1.88192427e-02  1.16094920e-01
  -1.87618074e-01 -2.82530356e-02  6.03805122e-02  7.88773308e-02
  -3.89452161e-02 -1.41096822e-01 -2.38101701e-01  1.45941513e-02
   1.17615896e-01 -9.90703404e-02  1.10595179e-01 -2.47810872e-01
  -1.44065778e-01 -2.69514440e-02 -2.68810689e-01 -2.32335232e-01
   2.77959131e-01  4.25542643e-02  2.21056166e-01 -6.89564341e-02
   5.99241927e-02 -3.45669103e-02 -1.11935913e-01  1.92940266e-01])

SyntaxError: invalid syntax (3497165141.py, line 1)

# PyMagnitude

In [1]:
import pymagnitude

model_path='../../models/embeddings/wiki.de.vec.magnitude'
vectors = pymagnitude.Magnitude(model_path)

# Get the vector representation of the query "hello world"
query_vec = vectors.query("hello world")

print(query_vec)

ModuleNotFoundError: No module named 'pymagnitude'

# Sentiment Transformers Oliverguhr german Bert

In [20]:
from typing import List
import torch
import re
import nltk
from nltk import word_tokenize, sent_tokenize

class SentimentModel():
    def __init__(self, model_name: str = "oliverguhr/german-sentiment-bert"):
        if torch.cuda.is_available():
            self.device = 'cuda'
        else:
            self.device = 'cpu'

        self.model = AutoModelForSequenceClassification.from_pretrained(model_name)
        self.model = self.model.to(self.device)
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)

        self.clean_chars = re.compile(r'[^A-Za-züöäÖÜÄß ]', re.MULTILINE)
        self.clean_http_urls = re.compile(r'https*\S+', re.MULTILINE)
        self.clean_at_mentions = re.compile(r'@\S+', re.MULTILINE)

    def predict_sentiment(self, texts: List[str]) -> List[str]:
        texts = [self.clean_text(text) for text in texts]
        # Add special tokens takes care of adding [CLS], [SEP], <s>... tokens in the right way for each model.
        # truncation=True limits number of tokens to model's limitations (512)
        encoded = self.tokenizer.batch_encode_plus(texts, padding=True, add_special_tokens=True, truncation=True,
                                                   return_tensors="pt")
        encoded = encoded.to(self.device)
        with torch.no_grad():
            logits = self.model(**encoded)

        # Array structure: [pos, neg, neu]
        probs = torch.nn.functional.softmax(logits[0], dim=-1).tolist()  # EDITED TO GET PROBABILITIES
        label_ids = torch.argmax(logits[0], axis=1)
        return ([self.model.config.id2label[label_id.item()] for label_id in label_ids], probs)

    def replace_numbers(self, text: str) -> str:
        return text.replace("0", " null").replace("1", " eins").replace("2", " zwei") \
            .replace("3", " drei").replace("4", " vier").replace("5", " fünf") \
            .replace("6", " sechs").replace("7", " sieben").replace("8", " acht") \
            .replace("9", " neun")

    def clean_text(self, text: str) -> str:
        text = text.replace("\n", " ")
        text = self.clean_http_urls.sub('', text)
        text = self.clean_at_mentions.sub('', text)
        text = self.replace_numbers(text)
        text = self.clean_chars.sub('', text)  # use only text chars                          
        text = ' '.join(text.split())  # substitute multiple whitespace with single whitespace   
        text = text.strip().lower()
        return text

In [21]:
def calc_sentiment_scores(text):
    sid = SentimentModel()
    neg = []
    neu = []
    pos = []


    sentences = nltk.tokenize.sent_tokenize(text)
    neg_temp = []
    pos_temp = []
    neu_temp = []
    for sentence in sentences:
        # If the sentence is smaller than 4 words (punctuation included)
        # sentiment results are all over the place
        if len(word_tokenize(sentence)) < 4:
            continue
        # print(sentence)
        sentiments, probs = sid.predict_sentiment([sentence])
        # print(probs)
        pos_temp.append(round(probs[0][0], 3))
        neg_temp.append(round(probs[0][1], 3))
        neu_temp.append(round(probs[0][2], 3))
    # print(pos)
    pos.append(np.mean(pos_temp))
    # print(pos)
    neg.append(np.mean(neg_temp))
    neu.append(np.mean(neu_temp))
    print(neg)

    neg = np.array(neg).reshape(-1, 1)
    print(neg)
    neu = np.array(neu).reshape(-1, 1)
    pos = np.array(pos).reshape(-1, 1)

    return np.concatenate([neg, pos, neu], axis=1)

In [23]:
sentiment = calc_sentiment_scores("hallo! wie gehts dir? super tag heute")
print(sentiment)

[0.929]
[[0.929]]
[[0.929 0.07  0.001]]


In [30]:
print(np.array(sentiment).reshape(-1, 1))

[[0.929]
 [0.07 ]
 [0.001]]


# Sentiment Transformers Model XLM roberta

In [24]:
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer, AutoConfig
import numpy as np
from scipy.special import softmax

# Preprocess text (username and link placeholders)
def preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

MODEL = f"cardiffnlp/twitter-xlm-roberta-base-sentiment"

tokenizer = AutoTokenizer.from_pretrained(MODEL)
config = AutoConfig.from_pretrained(MODEL)

# PT
model = AutoModelForSequenceClassification.from_pretrained(MODEL)
model.save_pretrained(MODEL)
tokenizer.save_pretrained(MODEL)

text = "hallo! wie gehts dir? super tag heute"
text = preprocess(text)
encoded_input = tokenizer(text, return_tensors='pt')
output = model(**encoded_input)
scores = output[0][0].detach().numpy()
scores = softmax(scores)


# Print labels and scores
ranking = np.argsort(scores)
ranking = ranking[::-1]
for i in range(scores.shape[0]):
    l = config.id2label[ranking[i]]
    s = scores[ranking[i]]
    print(f"{i+1}) {l} {np.round(float(s), 4)}")
    
print(ranking)
print(scores)

1) positive 0.8387
2) neutral 0.1454
3) negative 0.0159
[2 1 0]
[0.01590338 0.14535907 0.8387375 ]


# Punctuation count

In [31]:
import string
def count_punctuations(text):
    puncts = []
    punctuations = set(string.punctuation)
    count = lambda l1,l2: sum([1 for x in l1 if x in l2])
    puncts.append(count(text,punctuations))
    
    return np.array(puncts).reshape(-1,1)

In [32]:
print(count_punctuations("hallo! wie gehts dir? super tag heute."))

[[3]]


# Text features

In [33]:
def text_features(text):
    longest_word_length = []
    mean_word_length = []
    length_in_chars = []

    length_in_chars.append(len(text))
    longest_word_length.append(len(max(text.split(), key=len)))
    mean_word_length.append(np.mean([len(word) for word in text.split()]))

    longest_word_length = np.array(longest_word_length).reshape(-1, 1)
    mean_word_length = np.array(mean_word_length).reshape(-1, 1)
    length_in_chars = np.array(length_in_chars).reshape(-1, 1)

    return np.concatenate([longest_word_length, mean_word_length, length_in_chars], axis=1)

In [34]:
print(text_features("hallo! wie gehts dir? super tag heute."))

[[ 6.          4.57142857 38.        ]]


# New fastText

In [56]:
from typing import List
import pandas as pd
import fasttext
from tqdm import tqdm_notebook
from nltk import word_tokenize, sent_tokenize
import numpy as np

def fasttext_embeddings(df, idf_dict, model) -> List[float]:
    vectors = []
    for text in tqdm_notebook(df.text.values):
        w2v_vectors = []
        weights = []
        for word in word_tokenize(text):
            try:
                # If the word is in the vocabulary, return its embedding
                vector = model[word]
            except KeyError:
                # If the word is not in the vocabulary, get the embedding of its subwords
                subwords = model.get_subwords(word)
                if len(subwords) > 0:
                    subword_embeddings = [model.get_word_vector(subword) for subword in subwords]
                    vector = np.mean(subword_embeddings, axis=0)
                else:
                    # If the word and its subwords are not in the vocabulary, return None
                    vector = None
            w2v_vectors.append(vector)
            weights.append(idf_dict.get(word, 1))
        vectors.append(np.average(w2v_vectors, axis = 0, weights = weights))
    print(np.array(vectors).size)
    print(np.array(vectors).shape)
    return np.array(vectors)

In [57]:
d = {'text': ["hallo test text 1", "test text2", "noch ein text nummer 3"]}
df = pd.DataFrame(data=d)

In [58]:
df

text
0       hallo test text 1
1              test text2
2  noch ein text nummer 3

In [59]:
idf_dict = {'auch': 1.0, 'dies': 1.0, 'diesmal': 1.0, 'doppelt': 1.0, 'ein': 1.0, 'fügen': 1.0, 'hallo': 1.0, 'hinzu': 1.0, 'im': 1.0, 'ist': 1.0, 'manche': 1.0, 'noch': 1.0, 'sollen': 1.0, 'test': 1.0, 'text': 1.0, 'vorkommen': 1.0, 'weise': 1.0, 'weitere': 1.0, 'wir': 1.0, 'worte': 1.0}

In [63]:
model_path='../../models/embeddings/fastText.300.bin'
model = fasttext.load_model(model_path)

In [64]:
fasttext_embeddings(df, idf_dict, model)

C:\Users\Joel\AppData\Local\Temp\ipykernel_16100\3704550039.py:10: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for text in tqdm_notebook(df.text.values):


  0%|          | 0/3 [00:00<?, ?it/s]

900
(3, 300)


array([[-5.57245499e-02, -4.61318800e-02, -4.87735027e-02,
        -4.11862293e-02, -4.29207692e-02, -3.84600367e-03,
        -4.02156552e-02,  2.08122786e-02, -7.82810152e-04,
         6.89406972e-02, -1.40179898e-01,  2.43945094e-03,
        -7.52108903e-02,  6.01536208e-02, -4.33068353e-02,
        -1.58215186e-02,  2.21758275e-02,  8.83461988e-02,
        -6.92135568e-02, -1.08139287e-01, -5.02664866e-02,
         6.99156057e-02,  4.76662815e-03,  2.33393693e-02,
        -3.28041923e-02,  2.76385183e-02, -1.14654179e-03,
         2.89981328e-02, -5.60186007e-02,  2.00170563e-02,
        -2.76690582e-03,  9.82630032e-03,  4.82663605e-02,
         1.61939068e-02, -5.27699320e-02, -4.96995043e-02,
         6.37732577e-02,  5.00381412e-02,  2.79426835e-02,
         6.96885698e-02, -6.60432526e-03, -1.12128651e-02,
         9.45695331e-02,  1.80075504e-03,  7.29615148e-03,
         1.97931256e-02,  3.44543357e-03,  3.19165299e-02,
         1.65598718e-02,  1.07263358e-01, -5.07178809e-0

In [41]:
weights = [idf_dict.get(w, 1) for w in word_tokenize("dies ist ein test text")]
print(weights)

[1.0, 1.0, 1.0, 1.0, 1.0]


In [42]:
weights = []
weights.append(idf_dict.get("dies", 1))
weights.append(idf_dict.get("ist", 1))
weights.append(idf_dict.get("ein", 1))
weights.append(idf_dict.get("test", 1))
weights.append(idf_dict.get("text", 1))
print(weights)

[1.0, 1.0, 1.0, 1.0, 1.0]


The fasttext model is quite big. lets try to quantize it

In [65]:
quantized_model_path = 'fastText.300.quantized.ftz'

# Load the model
model = fasttext.load_model(model_path)

# Quantize the model
model.quantize(input=model_path, qnorm=True, retrain=True, cutoff=100000)

# Save the quantized model
model.save_model(quantized_model_path)

ValueError: For now we only support quantization of supervised models

# New Sentiment XLMR test

In [73]:
from transformers import AutoModelForSequenceClassification
from transformers import TFAutoModelForSequenceClassification
from transformers import AutoTokenizer, AutoConfig
from scipy.special import softmax

def _preprocess(text):
    new_text = []
    for t in text.split(" "):
        t = '@user' if t.startswith('@') and len(t) > 1 else t
        t = 'http' if t.startswith('http') else t
        new_text.append(t)
    return " ".join(new_text)

def sentiment_analysis(df):
    # Preprocess text (username and link placeholders)

    MODEL = f"cardiffnlp/twitter-xlm-roberta-base-sentiment"

    tokenizer = AutoTokenizer.from_pretrained(MODEL)
    config = AutoConfig.from_pretrained(MODEL)

    # PT
    model = AutoModelForSequenceClassification.from_pretrained(MODEL)
    model.save_pretrained(MODEL)
    tokenizer.save_pretrained(MODEL)

    sentiments = []
    for text in df.text.values:
        text = _preprocess(text)
        encoded_input = tokenizer(text, return_tensors='pt')
        output = model(**encoded_input)
        scores = output[0][0].detach().numpy()
        scores = softmax(scores)
        sentiments.append(scores)
    
    # [neg, neu, pos]
    return np.array(sentiments)

In [74]:
sentiment_analysis(df)

array([[0.12481989, 0.7195059 , 0.15567416],
       [0.26906842, 0.57750887, 0.15342276],
       [0.19121833, 0.74213284, 0.06664883]], dtype=float32)

# Haystack documents 

In [22]:
from haystack.nodes.base import BaseComponent
from haystack.nodes import TransformersTranslator
from typing import List, Dict, Optional

class CustomTranslator(BaseComponent):
    outgoing_edges = 1

    def __init__(self):
        # Store all init params in component's config so that we can easily save and load it via YAML
        self.translator = TransformersTranslator(model_name_or_path=f'Helsinki-NLP/opus-mt-en-fr')
        
    def run(self, query, language='fr', **kwargs):
        return self.translator.run(kwargs['documents'])
    
    def run_batch(self, queries: List[str], my_optional_param: Optional[int]) -> Dict[str, str]:
        return self.translator.run(kwargs['documents'])

In [23]:
from haystack.pipelines import Pipeline
pipeline = Pipeline()
pipeline.add_node(component=CustomTranslator(), name='CustomTranslator', inputs=['Query'])

In [26]:
query = "What's the history of Quidditch?"
result = pipeline.run(query=query, params={"language": "fr"})
result['documents'][0].text

Exception: Exception while running node 'CustomTranslator': 'documents'
Enable debug logging to see the data that was passed when the pipeline failed.

# Rasa Conversation Endpoint API

In [3]:
import json
conv='{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","events":[{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"action","timestamp":1679141910.2501759529,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":12},"name":"action_session_start","policy":null,"confidence":1.0,"action_text":null,"hide_rule_turn":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"session_started","timestamp":1679141910.2502615452,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":13},"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"action","timestamp":1679141910.2502791882,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":14},"name":"action_listen","policy":null,"confidence":null,"action_text":null,"hide_rule_turn":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"user","timestamp":1679142150.4917826653,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":15},"text":"hi","parse_data":{"intent":{"name":"greet","confidence":0.9999992847},"entities":[],"text":"hi","message_id":"e578f2711ac64f27a0c5b354afe7a2b0","metadata":{},"text_tokens":[[0,2]],"intent_ranking":[{"name":"greet","confidence":0.9999992847},{"name":"bot_challenge","confidence":0.0000002408},{"name":"deny","confidence":0.000000175},{"name":"goodbye","confidence":0.0000001399},{"name":"affirm","confidence":0.0000001215},{"name":"mood_unhappy","confidence":0.000000038},{"name":"mood_great","confidence":0.0000000365}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rasa","message_id":"e578f2711ac64f27a0c5b354afe7a2b0","is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"user_featurization","timestamp":1679142150.5018410683,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":16},"use_text_for_featurization":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"action","timestamp":1679142150.5018565655,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":17},"name":"utter_greet","policy":"MemoizationPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"bot","timestamp":1679142150.5019516945,"metadata":{"utter_action":"utter_greet","model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":18},"text":"Hey! How are you?","data":{"elements":null,"quick_replies":null,"buttons":null,"attachment":null,"image":null,"custom":null},"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"action","timestamp":1679142150.5083882809,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":19},"name":"action_listen","policy":"MemoizationPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"user","timestamp":1679142390.9550118446,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":20},"text":"hallo dies ist ein test text lorem ipsum dolor sit amet","parse_data":{"intent":{"name":"greet","confidence":0.4047514498},"entities":[],"text":"hallo dies ist ein test text lorem ipsum dolor sit amet","message_id":"d40ad4ef33494630bb8b51255e57c74b","metadata":{},"text_tokens":[[0,5],[6,10],[11,14],[15,18],[19,23],[24,28],[29,34],[35,40],[41,46],[47,50],[51,55]],"intent_ranking":[{"name":"greet","confidence":0.4047514498},{"name":"mood_great","confidence":0.204546839},{"name":"bot_challenge","confidence":0.170268476},{"name":"mood_unhappy","confidence":0.1399322599},{"name":"deny","confidence":0.0519310795},{"name":"affirm","confidence":0.0242456067},{"name":"goodbye","confidence":0.0043243165}],"response_selector":{"all_retrieval_intents":[],"default":{"response":{"responses":null,"confidence":0.0,"intent_response_key":null,"utter_action":"utter_None"},"ranking":[]}}},"input_channel":"rasa","message_id":"d40ad4ef33494630bb8b51255e57c74b","is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"user_featurization","timestamp":1679142390.9649317265,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":21},"use_text_for_featurization":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"action","timestamp":1679142390.9649496078,"metadata":{"query_intent":{"name":"greet","score":-1.3857530355,"threshold":-1.0310945511,"severity":0.3546584845},"label_ranking":[{"name":"mood_great","score":1.9440969229,"threshold":-1.2006345987,"severity":-3.1447315216},{"name":"mood_unhappy","score":1.5606993437,"threshold":-1.127918601,"severity":-2.6886179447},{"name":"nlu_fallback","score":-1.3285272121,"threshold":null,"severity":null},{"name":"goodbye","score":-1.3601157665,"threshold":null,"severity":null},{"name":"restart","score":-1.3799036741,"threshold":null,"severity":null},{"name":"greet","score":-1.3857530355,"threshold":-1.0310945511,"severity":0.3546584845},{"name":"bot_challenge","score":-1.4138555527,"threshold":null,"severity":null},{"name":"back","score":-1.4762108326,"threshold":null,"severity":null},{"name":"deny","score":-1.4805110693,"threshold":-1.3753910065,"severity":0.1051200628},{"name":"session_start","score":-1.6135823727,"threshold":null,"severity":null}],"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":22},"name":"action_unlikely_intent","policy":"UnexpecTEDIntentPolicy","confidence":1.0,"action_text":null,"hide_rule_turn":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"action","timestamp":1679142390.9725646973,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":23},"name":"utter_greet","policy":"TEDPolicy","confidence":0.930875957,"action_text":null,"hide_rule_turn":false,"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"bot","timestamp":1679142390.9726576805,"metadata":{"utter_action":"utter_greet","model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":24},"text":"Hey! How are you?","data":{"elements":null,"quick_replies":null,"buttons":null,"attachment":null,"image":null,"custom":null},"is_flagged":false},{"sender_id":"2e14fc1bf1f64800b53a3244946e4905","event":"action","timestamp":1679142390.9789199829,"metadata":{"model_id":"d22244ae716b4846b330532a145fc3e5","rasa_x_flagged":false,"rasa_x_id":25},"name":"action_listen","policy":"TEDPolicy","confidence":0.9901733398,"action_text":null,"hide_rule_turn":false,"is_flagged":false}]}'
conv=json.loads(conv)

In [4]:
print(conv)

{'sender_id': '2e14fc1bf1f64800b53a3244946e4905', 'events': [{'sender_id': '2e14fc1bf1f64800b53a3244946e4905', 'event': 'action', 'timestamp': 1679141910.250176, 'metadata': {'model_id': 'd22244ae716b4846b330532a145fc3e5', 'rasa_x_flagged': False, 'rasa_x_id': 12}, 'name': 'action_session_start', 'policy': None, 'confidence': 1.0, 'action_text': None, 'hide_rule_turn': False, 'is_flagged': False}, {'sender_id': '2e14fc1bf1f64800b53a3244946e4905', 'event': 'session_started', 'timestamp': 1679141910.2502615, 'metadata': {'model_id': 'd22244ae716b4846b330532a145fc3e5', 'rasa_x_flagged': False, 'rasa_x_id': 13}, 'is_flagged': False}, {'sender_id': '2e14fc1bf1f64800b53a3244946e4905', 'event': 'action', 'timestamp': 1679141910.2502792, 'metadata': {'model_id': 'd22244ae716b4846b330532a145fc3e5', 'rasa_x_flagged': False, 'rasa_x_id': 14}, 'name': 'action_listen', 'policy': None, 'confidence': None, 'action_text': None, 'hide_rule_turn': False, 'is_flagged': False}, {'sender_id': '2e14fc1bf1f6

In [7]:
conv['events'][0]['event']

'action'